accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
        path('profile/<str:username>/', views.profile, name='profile'),
]

crde/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/comments/', views.comment_create, name='comment_create'),
    path(
        '<int:post_pk>/comments/<int:comment_pk>/delete/',
        views.comment_delete,
        name='comment_delete',
    ),
    path('<int:post_pk>/answer/<str:answer>/', views.answer, name='answer'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', related_name='followers', symmetrical=False)

posts/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    option1 = models.CharField(max_length=200)
    option2 = models.CharField(max_length=200)
    option1_count = models.IntegerField(default=0)
    option2_count = models.IntegerField(default=0)
    selected_option = models.CharField(max_length=200, blank=True)
    select1_contents = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='selected_option1_posts', blank=True)
    select2_contents = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='selected_option2_posts', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    image1 = models.ImageField(blank=True)
    image2 = models.ImageField(blank=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        label='ID',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        ),
    )

    email = forms.CharField(
        label='e-mail',
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'type': 'email',
            },
        ),
    )

    last_name = forms.CharField(
        label='성',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            },
        ),
    )

    first_name = forms.CharField(
        label='이름',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            },
        ),
    )

    password1 = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'type': 'password',
            },
        ),
    )

    password2 = forms.CharField(
        label='비밀번호 확인',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'type': 'password',
            },
        ),
    )

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields =(
            'username',
            'email',
            'last_name',
            'first_name',
            'password1',
            'password2',
            )


class CustomUserChangeForm(UserChangeForm):
    email = forms.CharField(
        label='e-mail',
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'type': 'email',
            },
        ),
    )

    last_name = forms.CharField(
        label='성',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            },
        ),
    )

    first_name = forms.CharField(
        label='이름',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            },
        ),
    )

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            'email',
            'last_name',
            'first_name',
            )
        

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        label='ID',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            },
        ),
    )

    password = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'type': 'password',
            },
        ),
    )

    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )
        

class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="기존 비밀번호",
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
            },
        ),
    )

    new_password1 = forms.CharField(
        label="새 비밀번호",
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
            },
        ),
    )

    new_password2 = forms.CharField(
        label="새 비밀번호 확인",
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
            },
        ),
    )

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('old_password', 'new_password1', 'new_password2')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, CustomUserChangeForm, CustomAuthenticationForm, CustomPasswordChangeForm
from django.contrib.auth import get_user_model

# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('posts:index')

    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('posts:index')
    else:
        form = CustomAuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect('posts:index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def delete(request):
    request.user.delete()
    return redirect('posts:index')


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('posts:index')
    else:
        form = CustomPasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)



def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


@login_required
def follow(request, user_pk):
    User = get_user_model()
    you = User.objects.get(pk=user_pk)
    me = request.user
    if you != me:
        if me in you.followers.all():
            you.followers.remove(me)
        else:
            you.followers.add(me)
    return redirect('accounts:profile', you.username)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block style %}
  <style>
    .wid {
      width: 500px;
    }

    p {
      display: grid;
      grid-template-columns: 1fr auto;
    }

    p span {
      grid-column: 1 / -1;
    }

    form ul li {
      font-size: small;
    }
  </style>
{% endblock style %}

{% block content %}
<div class="wid">
  <form action="{% url 'accounts:change_password' %}" style="width: 550px" method="POST" class="mx-auto m-5">
    <div class='mb-4'>
      <h3>비밀번호 변경</h3>
    </div>
    {% csrf_token %}
    {% for field in form %}
    <div class='d-flex align-items-center'>
      <div class='col-3'>{{ field.label }}</div>
      <div class='col-9'>{{ field }}</div>
    </div>
    <hr>
    {% endfor %}
    <input type="submit" value="비밀번호변경" class="btn btn-outline-secondary d-block w-100 mb-2">
    <a class="btn btn-outline-secondary d-block w-100" onclick='func()' href="{% url 'posts:index' %}" role="button">HOME</a>
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block style %}
  <style>
    .wid {
      width: 500px;
    }

    p {
      display: flex;
      justify-content: space-between;
    }

    #id_username,
    #id_passerd = {
      border: 1px solid grey;
      border-radius: 10px;
    }

  </style>
{% endblock style %}

{% block content %}
<div class="p-5 wid">
  <form action="{% url 'accounts:login' %}" method="POST" style="width: 300px" class="mx-auto m-5">
    <div class='mt-5 mb-4'>
      <h3>로그인</h3>
    </div>
    {% csrf_token %}
    {% for field in form %}
      <div class='d-flex align-items-center'>
        <div class='col-3'>{{ field.label }}</div>
        <div class='col-9'>{{ field }}</div>
      </div>
      <hr>
    {% endfor %}
    <input type="submit" value="Login" class="btn btn-outline-secondary d-block w-100 mb-3">
    <a class="btn btn-outline-secondary d-block w-100" onclick='func()' href="{% url 'posts:index' %}" role="button">HOME</a>
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
a {
  cursor: pointer;
}

tbody tr {
  transition: all 0.2s linear;
}

tbody tr:hover {
  transform: scale(1.005);
  box-shadow: 1px 1px 15px lightgray;
}

.padding {
  padding-top: 3rem;
}

.profile-img {
  width: 100px;
  height: 100%;
  border-radius: 50px;
  overflow: hidden;
}

.profile-img-small {
  width: 30px;
  height: 100%;
  border-radius: 15px;
  overflow: hidden;
}

.profile-form {
  max-width: 350px;
}

.no-width {
  width: 10%;
  vertical-align: middle;
}

.date-width {
  width: 10%;
  vertical-align: middle;
}

.option-img {
  height: 100%;
  width: 100%;
  line-height: 30px;
  object-fit: cover;
}

.img-form {
  width: 180px;
  height: 250px;
  overflow: hidden;
  border-radius: 8px;
  border: 0.1px solid lightgray;
}

.empty-img {
  width: 150px;
  opacity: 0.5;
}

.font-gray {
  color: gray;
  text-align: center;
}
{% endblock style %}


{% block content %}
  <div class='container padding'>
    {% comment %} 유저 프로필 {% endcomment %}
    <div class='d-flex justify-content-center gap-4 mb-5'>
      <img src="{% static 'img/no-profile.png' %}" alt="img" class='profile-img'>
      <div class='d-flex row profile-form'>
        <h4 class='mt-2'>
          <b>{{ person.username }}</b>님의 프로필
        </h4>

        {% comment %} 팔로우 및 언팔로우 버튼 {% endcomment %}
        <div class='d-flex align-items-center gap-3'>
            <div>
              <form action="{% url 'accounts:follow' person.pk %}" method="POST">
                {% csrf_token %}
                {% if request.user in person.followers.all %}
                  <input type="submit" value="UnFollow" class='btn btn-primary'>
                {% else %}
                  {% if request.user.is_authenticated %}
                  <input type="submit" value="Follow" class='btn btn-primary'>
                  {% else %}
                  <input type="submit" value="Follow" disabled class='btn btn-primary'>
                  {% endif %}
                {% endif %}
              </form>
            </div>

            {% comment %} 팔로워 수 및 팔로잉 수 modal 트리거 {% endcomment %}
            <p class='my-auto'><a data-bs-toggle="modal" data-bs-target="#followers">팔로워 <b>{{ person.followers.all|length }}</b></a> / <a data-bs-toggle="modal" data-bs-target="#followings">팔로잉 <b>{{ person.followings.all|length }}</b></a></p>
        </div>
      </div>
    </div>


    {% comment %} 해당 유저가 작성한 게시물 목록 {% endcomment %}
    {% if person.post_set.all %}
    <p><b>작성 게시물({{ person.post_set.all|length }})</b></p>
      <table class="table text-center mt-0 mb-5">
        <thead class="table-secondary">
          <tr>
            <th scope="col">No.</th>
            <th scope="col">제 목</th>
            <th scope="col">작성일</th>
          </tr>
        </thead>
        <tbody>
          {% for post in person.post_set.all|dictsortreversed:'created_at' %}

          <tr>
            {% comment %} 게시물 번호 {% endcomment %}
            <td scope="row" class='no-width'>
              {{ post.pk }}
            </td>

            {% comment %} 게시물 제목 {% endcomment %}
            <td>
              <a href="{% url 'posts:detail' post.pk %}" class='d-flex row'>
                <div class='d-flex justify-content-center gap-3'>
                  <div>
                    <div class='img-form mb-2'>
                      {% if post.image1 %}
                        <img src="{{ post.image1.url }}" alt="" class='option-img'>
                      {% else %}
                        <img src="{% static 'img/no-img.jpg' %}" alt="" class='option-img'>
                      {% endif %}
                    </div>
                    {{post.option1}}
                  </div>
                  <p class='my-auto'>VS</p>
                  <div>
                    <div class='img-form mb-2'>
                      {% if post.image2 %}
                        <img src="{{ post.image2.url }}" alt="" class='option-img'>
                      {% else %}
                        <img src="{% static 'img/no-img.jpg' %}" alt="" class='option-img'>
                      {% endif %}
                    </div>
                    {{post.option2}}
                  </div>
                </div>
              </a>
            </td>

            {% comment %} 게시물 작성일 {% endcomment %}
            <td class="text-secondary date-width">
              {{ post.created_at|date:"Y-m-d" }}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

    {% else %}
      {% comment %} 빈 작성 게시물 {% endcomment %}
      <hr>
      <div class='d-flex row justify-content-center mt-5'>
        <img src="{% static 'img/empty.png' %}" alt="" class='empty-img mt-5'>
        <h4 class='mt-5 font-gray'>생성된 밸런스 게임이 없습니다.</h4>
      </div>
    {% endif %}


    <!-- 팔로잉 Modal -->
    <div class="modal fade" id="followings" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">팔로잉</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            {% for following in person.followings.all %}
              <a href="{% url 'accounts:profile' following.username %}"class='d-flex gap-3 mb-3'>
                <img src="{% static 'img/no-profile.png' %}" alt="img" class='profile-img-small'>
                {{ following }}
              </a>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>

    <!-- 팔로워 Modal -->
    <div class="modal fade" id="followers" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">팔로워</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            {% for follower in person.followers.all %}
              <a href="{% url 'accounts:profile' follower.username %}" class='d-flex gap-3 mb-3'>
                <img src="{% static 'img/no-profile.png' %}" alt="img" class='profile-img-small'>
                {{ follower }}
              </a>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    {% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block style %}
  <style>
    .wid {
      width: 500px;
    }
    p {
      display: grid;
      grid-template-columns: 1fr auto;
    }

    p label {
      white-space: nowrap;
    }

    p span {
      grid-column: 1 / -1;
    }

  </style>
{% endblock style %}

{% block content %}
<div class="wid mt-3">
  <form action="{% url 'accounts:signup' %}" method="POST" style="width: 500px" class="mx-auto">
    <div class='mt-5 mb-4'>
      <h3>회원가입</h3>
    </div>
    {% csrf_token %}
    {% for field in form %}
    <div class='d-flex align-items-center'>
      <div class='col-3'>{{ field.label }}</div>
      <div class='col-9'>{{ field }}</div>
    </div>
    <hr>
    {% endfor %}
    <input type="submit" value="회원가입" class="btn btn-outline-secondary d-block w-100 mb-3">
    <a class="btn btn-outline-secondary d-block w-100" onclick='func()' href="{% url 'posts:index' %}" role="button">HOME</a>
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block style %}
  <style>
    .wid {
      width: 500px;
    }

    p {
      display: grid;
      grid-template-columns: 1fr auto;
    }

    p span {
      grid-column: 1 / -1;
    }
  </style>
{% endblock style %}

{% block content %}
<div class="wid">
  <form action="{% url 'accounts:update' %}" method="POST" style="width: 500px" class="mx-auto m-5 mb-3">
    <div class='mt-5 mb-4'>
      <h3>회원정보 수정</h3>
    </div>
    {% csrf_token %}
    {% for field in form %}
    <div class='d-flex align-items-center'>
      <div class='col-3'>{{ field.label }}</div>
      <div class='col-9'>{{ field }}</div>
    </div>
    <hr>
    {% endfor %}
    <input type="submit" value="회원정보수정" class="btn btn-outline-secondary d-block w-100"> 
    <a class="btn btn-outline-secondary d-block w-100 my-3" onclick='func()' href="{% url 'accounts:change_password' %}" role="button">비밀번호 변경</a>
  </form>
  <form action="{% url 'accounts:delete' %}" method="POST" style="width: 500px" class="mx-auto m-5 mt-0">
    {% csrf_token %}
    <input class="btn btn-outline-secondary d-block w-100 mb-3" type="submit" value="회원탈퇴" onclick="return confirm('탈퇴 하시겠습니까?')">
    <a class="btn btn-outline-secondary d-block w-100" onclick='func()' href="{% url 'posts:index' %}" role="button">HOME</a>
  </form>

</div>
{% endblock content %}