accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
        path('profile/<str:username>/', views.profile, name='profile'),
]

crde/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/comments/', views.comment_create, name='comment_create'),
    path(
        '<int:post_pk>/comments/<int:comment_pk>/delete/',
        views.comment_delete,
        name='comment_delete',
    ),
    path('<int:post_pk>/answer/<str:answer>/', views.answer, name='answer'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Review</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <style>
      a {
        text-decoration: none;
        color: black;
      }

      .logo-img {
        width: 50px;
      }
      {% block style %}
      {% endblock style %}
    </style>

  </head>
  <body>
    <nav class="navbar bg-body-secondary">
      <div class="container">
        <a class="navbar-brand d-flex align-items-center gap-4" href="{% url 'posts:index' %}">
          <img src="{% static 'img/scale.png' %}" alt="" class='logo-img'>
          <h3><b>BELLRUNS</b></h3>
        </a>
        <div class="d-flex">
          {% if request.user.is_authenticated %}
            <p class="m-0 me-2 align-self-center no_wrap text-secondary"><a href="{% url 'accounts:profile' user %}"><b>{{ user }}</b>님 안녕하세요!</p>
            <form action="{% url 'accounts:logout' %}" method="POST">
              {% csrf_token %}
              <input class="btn btn-outline-secondary me-2" type="submit" value="Logout">
            </form>
            <a class="btn btn-outline-secondary no_wrap me-2" href="{% url 'accounts:update' %}" role="button">회원정보수정</a>
            <a href="{% url 'posts:create' %}" class="btn btn-outline-secondary" role="button">게임생성</a>
          {% else %}
            <a class="btn btn-outline-secondary me-2" href="{% url 'accounts:login' %}" role="button">LOGIN</a>
            <a class="btn btn-outline-secondary me-2" href="{% url 'accounts:signup' %}" role="button">SIGN UP</a>
          {% endif %}
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock content %}
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

templates/footer.html
<div style = "text-align:center; margin-top:2px; bottom: 0;">
    <div style="font-size:.8rem;">
        <a class='' href="https://github.com/HyeonSeuk">서현석</a> |
        <a class='' href="https://github.com/JeonggonCho">조정곤</a> |
        <a class='' href="https://github.com/jangjaeyong1115">장재용</a>
    </div>
    <div style="margin-top:1rem;">
        <h6>&copy KDT 실습 1조</h6>
    </div>

</div>