accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
        path('profile/<str:username>/', views.profile, name='profile'),
]

crde/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/comments/', views.comment_create, name='comment_create'),
    path(
        '<int:post_pk>/comments/<int:comment_pk>/delete/',
        views.comment_delete,
        name='comment_delete',
    ),
    path('<int:post_pk>/answer/<str:answer>/', views.answer, name='answer'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
]

posts/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    option1 = models.CharField(max_length=200)
    option2 = models.CharField(max_length=200)
    option1_count = models.IntegerField(default=0)
    option2_count = models.IntegerField(default=0)
    selected_option = models.CharField(max_length=200, blank=True)
    select1_contents = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='selected_option1_posts', blank=True)
    select2_contents = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='selected_option2_posts', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    image1 = models.ImageField(blank=True)
    image2 = models.ImageField(blank=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    option1 = forms.CharField(
        label='Option1',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        ),
    )

    image1 = forms.ImageField(
        label='Option1-이미지',
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control',
            },
        ),
        required=False,
    )

    option2 = forms.CharField(
        label='Option2',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        ),
    )

    image2 = forms.ImageField(
        label='Option2-이미지',
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control',
            },
        ),
        required=False,
    )

    class Meta:
        model = Post
        fields = ('option1', 'image1', 'option2', 'image2',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
    content = forms.CharField(
        widget=forms.TextInput(
        attrs={
            'class' : 'form-control',
            'style' : 'width: 250px'
        }
        )
    )

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.core.paginator import Paginator


# Create your views here.
def index(request):
    posts = Post.objects.all().order_by('-created_at')
    page = request.GET.get('page', '1')
    per_page = 5
    paginator = Paginator(posts, per_page)
    page_obj = paginator.get_page(page)
    context = {
        'posts': page_obj,
    }
    return render(request, 'posts/index.html', context)


@login_required
def detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    comment_form = CommentForm()
    comments = post.comment_set.all()
    if request.method == 'POST':
        answer = request.POST.get('answer','')
        if answer == post.option1 and request.user not in post.select1_contents.all():
            post.option1_count += 1
            post.selected_option = post.option1
            post.select1_contents.add(request.user)
            post.select2_contents.remove(request.user)
        elif answer == post.option2 and request.user not in post.select2_contents.all():
            post.option2_count += 1
            post.selected_option = post.option2
            post.select2_contents.add(request.user)
            post.select1_contents.remove(request.user)
        post.save()

    context = {
        'post': post,
        'comment_form':comment_form,
        'comments': comments,
        }
    return render(request, 'posts/detail.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        option1 = request.POST['option1']
        option2 = request.POST['option2']
        image1 = request.FILES.get('image1')
        image2 = request.FILES.get('image2')
        user = request.user
        post = Post.objects.create(option1=option1, option2=option2, image1=image1, image2=image2, user=user)
        return redirect('posts:detail', post_pk=post.pk)
    return render(request, 'posts/create.html')


@login_required
def delete(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.user == post.user:
        post.delete()
    return redirect('posts:index')


@login_required
def update(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.user == post.user:
        if request.method == 'POST':
            form = PostForm(request.POST, request.FILES, instance=post)
            if form.is_valid():
                form.save()
                return redirect('posts:detail', post.pk)
        else:
            form = PostForm(instance=post)
    else:
        return redirect('posts:detail', post_pk)
    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'posts/update.html', context)


@login_required
def comment_create(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.post = post
        comment.user = request.user
        comment.save()
        return redirect('posts:detail', post.pk)
    context = {
        'post': post,
        'comment_form': comment_form,
    }
    return render(request, 'posts/detail.html', context)


@login_required
def comment_delete(request, post_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)

    if request.user == comment.user:
        comment.delete()
    return redirect('posts:detail', post_pk)


@login_required
def answer(request, post_pk, answer):
    post = get_object_or_404(Post, pk=post_pk)
    if answer == '1':
        post.select1_contents.add(request.user)
    elif answer == '2':
        post.select2_contents.add(request.user)
    else:
        pass
    return redirect('posts:detail', pk=post_pk)


@login_required
def likes(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.user in post.like_users.all():
        post.like_users.remove(request.user)
    else:
        post.like_users.add(request.user)
    return redirect('posts:index')

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block style %}
  <style>
    .wid {
      width: 500px;
    }

    p {
      display: grid;
      grid-template-columns: 1fr auto;
    }

    p span {
      grid-column: 1 / -1;
    }

    .option1 {
      background-color: #f6f6f6;
      border: 1px solid lightgray;
      border-radius: 10px;
    }

    .option2 {
      background-color: #f6f6f6;
      border: 1px solid lightgray;
      border-radius: 10px;
    }
  </style>
{% endblock style %}

{% block content %}
<div class="wid">
  <form method="POST" enctype="multipart/form-data" style="width: 500px" class="mx-auto m-5 mb-3">
    <div class='mb-4'>
      <h3>게임생성</h3>
    </div>
    {% csrf_token %}
    <div class='option1 p-2'>
      <div class="form-group mb-3">
        <label for="option1">Option 1</label>
        <input type="text" name="option1" required class="form-control">
      </div>
      <div class="form-group mb-3">
        <label for="image1">Option 1-이미지</label>
        <input type="file" name="image1" class="form-control">
      </div>
    </div>

    <div class='d-flex justify-content-center my-3'>
      <p><b>VS</b></p>
    </div>

    <div class='option2 p-2'>
      <div class="form-group mb-3">
        <label for="option2">Option 2</label>
        <input type="text" name="option2" required class="form-control">
      </div>
      <div class="form-group mb-3">
        <label for="image2">Option 2-이미지</label>
        <input type="file" name="image2" class="form-control">
      </div>
    </div>
    <button type="submit" class="btn btn-outline-secondary d-block w-100 mt-4">게임 생성</button>
  </form>
</div>
{% endblock %}

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<style>
  .c{
    height: 400px;
    object-fit: cover;
  }
  label {
    display: inline-block;
    vertical-align: middle;
    padding-top: 5px;
    margin-right: 10px;
  }
  .card-img-top {
    height: 400px;
    object-fit: cover;
  }
  #id_content {
    margin-right: 10px;
  }
  .pad {
    padding-top: 5px;
  }
</style>
{% endblock style %}

{% block content %}
<main class = "container text-center">
  <h1 class="my-4">BELLRUNS GAME</h1>

  <p>게임 제작 -
    <a href="{% url 'accounts:profile' post.user.username %}">
    {{ post.user }}</a></p>
  <p>
    게임 번호 -
    {{ post.pk }}
  </p>
  
  <form method="POST">
    {% csrf_token %}
    <!-- detail 사진 위에 글씨 -->
    <div class="container">
      <div class="row justify-content-center align-items-center">
        <h2 class="col-sm-2 text-center">
          {{ post.option1 }}
        </h2>
        <h2 class="col-sm-1 text-center">
          vs
        </h2>
        <h2 class="col-sm-2 text-center">
          {{ post.option2 }}
        </h2>
      </div>
    </div>
    <!-- detail 사진 -->
    <div class="container">
      <div class='row justify-content-center align-items-center'>
        <div class="col-6 col-md-6 col-lg-3">
          <div class="card" style="width: 18rem;">
            <div class="c">
              {% if post.image1 %}
                <img src="{{ post.image1.url }}" class="card-img-top" alt="">
              {% else %}
                <img src="{% static 'img/no-img.jpg' %}" class="card-img-top" alt="">
              {% endif %}
            </div>
            <div class="card-body text-center">
              <button type="submit" class="btn btn-outline-secondary" name="answer" value="{{ post.option1 }}" {% if post.selected_option == post.option1 %}disabled{% endif %}>
                {{ post.option1 }} ({{ post.option1_count }})
              </button>
            </div>
          </div>
        </div>
        <div class="col-6 col-md-6 col-lg-3">
          <div class="card" style="width: 18rem;">
            <div class="c">
              {% if post.image2 %}
                <img src="{{ post.image2.url }}" class="card-img-top" alt="">
              {% else %}
                <img src="{% static 'img/no-img.jpg' %}" class="card-img-top" alt="">
              {% endif %}
            </div>
            <div class="card-body mx-auto">
              <button type="submit" class="btn btn-outline-secondary" name="answer" value="{{ post.option2 }}" {% if post.selected_option == post.option2 %}disabled{% endif %}>
                {{ post.option2 }} ({{ post.option2_count }})
              </button>
            </div>
          </div>
        </div>
    </div>

    <!-- 해당 코드 없애면 수정 및 생성, 삭제 오류 발생 -->
    {% if request.user == post.user %}
    <form action="{% url 'posts:delete' post.pk %}" method="POST">
      {% csrf_token %}
    </form>
  {% endif %}

    <!-- 공유하기 Modal -->
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      {% if request.user == post.user %}
      <form action="{% url 'posts:delete' post.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="DELETE" class="btn btn-outline-secondary me-2" onclick="return confirm('삭제 하시겠습니까?')">
      </form>
      <a class="btn btn-outline-secondary me-2" href="{% url 'posts:update' post.pk %}" role="button">UPDATE</a>
    {% endif %}
    <button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      공유하기
    </button>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">공유하기</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class ="mx-auto">
              <a class='btn btn-outline-primary' href="https://www.facebook.com">페이스북</a>
              <a class='btn btn-outline-danger' href="https://www.instagram.com">인스타그램</a>
              <a class='btn btn-outline-info' href="https://twitter.com/">트위터</a>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">닫기</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  </form>
  
  <hr>
  <!-- 댓글 form -->
  <div class="container">
    <form action="{% url 'posts:comment_create' post.pk %}" method="POST" class="d-flex justify-content-center">
      {% csrf_token %}
      {{ comment_form }}
      <input type="submit" value="댓글 작성" class="btn btn-outline-secondary">
    </form>
  </div>

  <hr>

  <!-- 댓글 작성란 -->
  {% for comment in comments %}
  <li class="d-flex justify-content-center align-self-center my-4">
    <div class="d-flex flex-column">
      <div class="d-flex justify-content-between align-items-center w-100">
        <p class="me-2 mb-0 pad">댓글 작성자 - <a href="{% url 'accounts:profile' comment.user.username %}">{{ comment.user }}</a> /</p>
        <p class="me-2 mb-0 pad">댓글 번호 - {{ forloop.counter }} /</p>
        <p class="me-2 mb-0 pad">댓글 내용: {{ comment.content }}</p>
        {% if comment.user == user %}
          <form action="{% url 'posts:comment_delete' post.pk comment.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-outline-secondary" value="댓글 삭제">
          </form>
        {% endif %}
      </div>
    </div>
  </li>
  {% empty %}
    <p>댓글이 없어요</p>
  {% endfor %}
</main>


<script>
    // 이전에 선택한 버튼이 있는 경우, 해당 버튼의 value 값을 가져옵니다.
    var selectedValue = "{{ post.selected_option }}";
    var buttons = document.querySelectorAll('button[name="answer"]');
  
    // 모든 버튼을 돌면서
    buttons.forEach(function(button) {
      // 선택한 버튼이 이미 선택된 버튼이면
      if (selectedValue == button.value) {
        // 모든 버튼을 disable 처리합니다.
        buttons.forEach(function(disableButton) {
          disableButton.disabled = true;
        });
  
        // 선택된 버튼만 enable 처리합니다.
        button.disabled = false;
      }
    });
</script>
{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<style>
  .c{
    height: 300px;
    object-fit: cover;
  }

  .card-img-top {
    width: 300px;
    height: 300px;
    object-fit: cover;
  }

  .game-form {
    border: 1px solid lightgray;
    border-radius: 10px;
    width: 1000px;
    margin: auto;
  }

  .like {
    background-color: transparent;
    transition: all 0.1s linear;
  }

  .like:hover {
    transform: scale(1.3);
  }

  .like:active {
    color: lightgray;
  }

  .like-red {
    color: red;
    background-color: transparent;
    transition: all 0.1s linear;
  }

  .like-red:hover {
    transform: scale(1.3);
  }

  .material-symbols-outlined {
    font-variation-settings:
    'FILL' 1,
    'wght' 300,
    'GRAD' 0,
    'opsz' 48
  }

  .post-user {
    color: gray;
    font-size: 14px;
  }
  
  .post-user:hover {
    color: black;
  }

  .width {
    width: 100px;
  }
</style>
{% endblock style %}

{% block content %}
<div class="container mt-5">
  <div class='d-flex row gap-3 justify-content-center'>
    {% for post in posts %}
      <div class="d-flex row p-4 game-form">
        <a href="{% url 'posts:detail' post.pk %}">
          <div class='d-flex justify-content-center gap-3'>
            <div class="card border-0">
              <div class="c">
                {% if post.image1 %}
                  <img class="card-img-top" src="{{ post.image1.url }}" alt="Image 1">
                {% else %}
                  <img class="card-img-top" src="{% static 'img/no-img.jpg' %}" alt="image1">
                {% endif %}
              </div>
              <div class="card-body text-center">
                <h5 class="card-title"><b>{{ post.option1 }}</b></h5>
              </div>
            </div>
            
            <div class="d-flex align-items-center justify-content-center">
              <h1>VS</h1>
            </div>
            <div class="card border-0">
              <div class="c">
                {% if post.image2 %}
                  <img class="card-img-top" src="{{ post.image2.url }}" alt="Image 2">
                {% else %}
                  <img class="card-img-top" src="{% static 'img/no-img.jpg' %}" alt="image2">
                {% endif %}
              </div>
              <div class="card-body text-center">
                <h5 class="card-title"><b>{{ post.option2 }}</b></h5>
              </div>
            </div>
          </div>
          <div class='d-flex justify-content-between'>
            <p class='my-auto flex-grow-1'>
              제작 : 
              <a href="{% url 'accounts:profile' post.user.username %}" class='post-user'>{{ post.user }}</a>
            </p>
            <form action="{% url 'posts:likes' post.pk %}" method="POST">
              {% csrf_token %}
              {% if request.user in post.like_users.all %}
                <button type="submit" class="border-0 like-red">
                  <span class="material-symbols-outlined">
                    favorite
                  </span>
                </button>
              {% else %}
                <button type="submit" class="border-0 like">
                  <span class="material-symbols-outlined">
                    favorite
                  </span>
                </button>
              {% endif %}
            </form>
          </div>
        </a>
      </div>
    {% endfor %}
  </div>

  {% comment %} 페이지네이션 작성 {% endcomment %}
  <ul class='pagination justify-content-center my-5'>
    {% if posts.has_previous %}

      {% comment %} 처음으로 버튼 (페이지를 1로 설정) {% endcomment %}
      <li class='page-item'>
        <a class='page-link' href="?page=1">처음</a>
      </li>

      <li class='page-item'>
        <a class='page-link' href="?page={{ posts.previous_page_number }}">이전</a>
      </li>
    {% else %}
      <li class='page-item disabled'>
        <a class='page-link' tabindex='-1' aria-disabled='true' href="#">이전</a>
      </li>
    {% endif %}
    {% for page_number in posts.paginator.page_range %}
      {% if page_number >= posts.number|add:-5 and page_number <= posts.number|add:5 %}
        {% if page_number == posts.number %}
          <li class='page-item active' aria-current='page'>
            <a class='page-link' href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% else %}
          <li class='page-item'>
            <a class='page-link' href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% endif %}
      {% endif %}
    {% endfor %}
    {% if posts.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.next_page_number }}">다음</a>
      </li>

      {% comment %} 마지막으로 버튼 (페이지를 전체페이지 수로 설정) {% endcomment %}
      <li class="page-item">
        <a class="page-link" href="?page={{ posts.paginator.num_pages }}">마지막</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
      </li>
    {% endif %}
  </ul>
</div>
{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block style %}
  <style>
    .wid {
      width: 500px;
    }

    p {
      display: grid;
      grid-template-columns: 1fr auto;
    }

    p span {
      grid-column: 1 / -1;
    }
  </style>
{% endblock style %}

{% block content %}
<div class="wid">
  <form method="POST" enctype="multipart/form-data" style="width: 500px" class="mx-auto m-5 mb-3">
    <div class='mb-4'>
      <h3>게임 수정</h3>
    </div>
    {% csrf_token %}
    {% for field in form %}
      <div class='mb-3'>
        <div>{{ field.label }}</div>
        <div>{{ field }}</div>
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-outline-secondary d-block w-100 mt-4">게임 수정</button>
  </form>
</div>
{% endblock %}